apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-canary
  namespace: idle-battle
  labels:
    app: idle-battle
    version: "{{ .Values.canary.image.tag }}"
    canary: "true"
spec:
  replicas: {{ .Values.canary.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: web
      canary: "true"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
        canary: "true"
    spec:
      containers:
        - name: web
          image: "{{ .Values.canary.image.repository }}:{{ .Values.canary.image.tag }}"
          imagePullPolicy: {{ .Values.canary.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http