apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: web-dr
  namespace: idle-battle
spec:
  host: web-svc.idle-battle.svc.cluster.local
  subsets:
  - name: production
    labels:
      canary: "false"
  - name: canary
    labels:
      canary: "true"