apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: idle-battle
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: web
