apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-vs
  namespace: idle-battle
spec:
  hosts:
    - "*"
  gateways:
    - idle-battle-gateway
  http:
    - route:
      - destination:
          host: web-svc.idle-battle.svc.cluster.local
          subset: production
        weight: {{ .Values.canary.prodWeight }}
      - destination:
          host: web-svc.idle-battle.svc.cluster.local
          subset: canary
        weight: {{ .Values.canary.canaryWeight }}